### ISSUE TITLE
Undefined name: commands in octosuite.py

### ISSUE THREAD

**Issue by cclauss** [bellingcat/octosuite#10]
Undefined name: [`commands`](https://github.com/bellingcat/octosuite/blob/master/octosuite/octosuite.py#L38) in `octosuite.py`.  The variable `commands` is not defined or imported in this file.

% `flake8 . --count --select=E9,F63,F7,F82,Y --show-source --statistics`
```
./octosuite/octosuite.py:38:31: F821 undefined name 'commands'
        options = [i for i in commands if i.startswith(text)]
                              ^
1     F821 undefined name 'commands'
1
```

**Comment by rly0nheart** [comment]
This code is using the readline (for unix-like systems) library to enable tab completion for a list of commands. The completer function takes in the text entered so far and the current state of the completion, and returns the next option that matches the text if one exists. The parse_and_bind and set_completer methods are used to activate the completer function when the tab key is pressed.

On unix-like machines, this code does not return any errors

**Comment by cclauss** [comment]
Where is `commands` defined?

**Comment by rly0nheart** [comment]
It is never defined and it doesn't return an error

**Comment by cclauss** [comment]
OK.  `global commands` or `nonlocal commands` would placate the linter but I think we can close this.
