### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PierrunoYT** [bellingcat/octosuite#15]
C:\Users\pierr\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\config\_apply_pyprojecttoml.py:103: _WouldIgnoreField: 'entry-points' defined outside of `pyproject.toml` would be ignored.
    !!

    ##########################################################################
    # configuration would be ignored/result in error due to `pyproject.toml` #
    ##########################################################################

    The following seems to be defined outside of `pyproject.toml`:

    `entry-points = {'console_scripts': ['octosuite=octosuite.main:octosuite']}`

    According to the spec (see the link below), however, setuptools CANNOT
    consider this value unless 'entry-points' is listed as `dynamic`.

    https://packaging.python.org/en/latest/specifications/declaring-project-metadata/

    For the time being, `setuptools` will still consider the given value (as a
    **transitional** measure), but please note that future releases of setuptools will
    follow strictly the standard.

    To prevent this warning, you can list 'entry-points' under `dynamic` or alternatively
    remove the `[project]` table from your file and rely entirely on other means of
    configuration.

!!

  warnings.warn(msg, _WouldIgnoreField)
C:\Users\pierr\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\config\_apply_pyprojecttoml.py:196: UserWarning: `install_requires` overwritten in `pyproject.toml` (dependencies)
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

C:\Users\pierr\octosuite>

**Comment by rly0nheart** [comment]
Hello @PierrunoYT, thanks for this, I will look into it and will let you know once it's fixed.

**Comment by rly0nheart** [comment]
Hey there @PierrunoYT , I have updated the pyproject.toml file, could you try again and let me know how it goes?

Also I would appreciate it if you showed the steps you took to produce that error :)

**Comment by PierrunoYT** [comment]
Hey there

I could not test it yet but I will try in the next days.

Thank you.

Best,
Pierre

Von: Richard ***@***.***>
Gesendet: Freitag, 24. Februar 2023 01:43
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [bellingcat/octosuite] Error (Issue #15)


Hey there @PierrunoYT<https://github.com/PierrunoYT> , I have updated the pyproject.toml file, could you try again and let me know how it goes?

Also I would appreciate it if you showed the steps you took to produce that error :)

**Comment by rly0nheart** [comment]
Alright, enjoy!😊
