### ISSUE TITLE
Organi{z}ation prompt: minor spelling mistake

### ISSUE THREAD

**Issue by WarthogARJ** [bellingcat/octosuite#16]
Prompt for "Organization" is output as "@Organiation" instead of "@Organization"
That is, the "z" is missing.

This is due to line 1056 in octosuite.py:
organization = Prompt.ask(f"{white}@{green}Organi[sz]ation{reset}")

If written as follows, then correct spelling:
organization = Prompt.ask(f"{white}@{green}Organization{reset}")

Perhaps code had [sz} in it to allow for alternate US/UK-english spellings, but this doesn't seem to have desired effect in Python3.11 on Macos.

Personally, I view "organisation" as the preferred/correct way to spell "organization".
And since Bellingcat is a European organisation (sic), it seems to be more consisten to use English rather than US spelling.
Although after Brexxit, it is a bit harder to argue that case....sigh

**Comment by rly0nheart** [comment]
Lol agreed, I have made the changes in the dev branch, I will merge with master as soon as I finish making other updates as I want to publish a new release.

So I'll mark this as done.

**Comment by WarthogARJ** [comment]
Thankz....:-}

**Comment by rly0nheart** [comment]
Cool!, Were you just visiting or maybe that's where you're from?
