### ISSUE TITLE
An error occurred: 'Table' object has no attribute 'add_section'

### ISSUE THREAD

**Issue by NoneDev-git** [bellingcat/octosuite#5]
![image](https://user-images.githubusercontent.com/77238864/203094060-830fb56a-9875-4f41-bda2-c561b0bdb125.png)
When I call help, it gives an error.

**Comment by rly0nheart** [comment]
Hello, sorry about this.

I have fix it, you can try again now

It's strange though, it doesn't return that error on my system(s) (Windows, Ubuntu), but I tried using it one Kali virtual machine and I got the error.
But when I tried on another Kali virtual machine, I didn't get the error😅, I think it's probably an issue with the rich library.

Once again it's fixed now, enjoy!🙂

**Comment by rly0nheart** [comment]
Also, I noticed you're running it as root, could you try running it as a regular user, then let me know what happens?

**Comment by NoneDev-git** [comment]
I tried to run both root and normal.
![image](https://user-images.githubusercontent.com/77238864/203098420-de273de8-3dc5-405d-b6ad-bb9a9a21f35d.png)
I'm going to try again. Thanks for the quick support:)

**Comment by rly0nheart** [comment]
> I tried to run both root and normal. ![image](https://user-images.githubusercontent.com/77238864/203098420-de273de8-3dc5-405d-b6ad-bb9a9a21f35d.png) I'm going to try again. Thanks for the quick support:)

No problem, happy to be help!

Alright, if it doesn't work then you should just reclone the repository, I have already pushed the fix to that

**Comment by NoneDev-git** [comment]
![image](https://user-images.githubusercontent.com/77238864/203099854-530d585b-5b78-44b8-8630-074fde650561.png)
Problem solved! Thanks again. Very useful tool.

**Comment by rly0nheart** [comment]
> ![image](https://user-images.githubusercontent.com/77238864/203099854-530d585b-5b78-44b8-8630-074fde650561.png) Problem solved! Thanks again. Very useful tool.

Nice one!

Glad you find it useful, thank you.
